default_job = "clippy"

[jobs.check]
command = ["cargo", "check", "--workspace", "--all-targets", "--color", "always"]
need_stdout = false

[jobs.clippy]
command = ["cargo", "clippy", "--workspace", "--all-targets", "--color", "always"]
need_stdout = false

[jobs.test]
command = ["cargo", "nextest", "run", "--workspace", "--color", "always"]
need_stdout = true

[keybindings]
c = "job:clippy"
k = "job:check"
t = "job:test"
