{
  description = "Multi-machine nix-darwin + home-manager setup (hosts from nixup inventory)";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixpkgs-unstable";

    nix-darwin.url = "github:nix-darwin/nix-darwin/master";
    nix-darwin.inputs.nixpkgs.follows = "nixpkgs";

    home-manager.url = "github:nix-community/home-manager";
    home-manager.inputs.nixpkgs.follows = "nixpkgs";

    # Fork with kitty graphics protocol + yazi image rendering (default branch: main).
    zellij = {
      url = "github:kaankoken/zellij";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs =
    {
      self,
      nixpkgs,
      nix-darwin,
      home-manager,
      zellij,
      ...
    }:
    let
      inherit (nixpkgs) lib;

      # Generated by `nixup hosts sync` from local nixup.toml (or use inventory.example.nix).
      inventory =
        if builtins.pathExists ./hosts/inventory.nix then
          import ./hosts/inventory.nix
        else
          import ./hosts/inventory.example.nix;

      overlays = [
        zellij.overlays.default
      ];

      # Shared special args for all modules
      mkSpecialArgs = system: {
        inherit self;
        flakeInputs = {
          inherit nixpkgs nix-darwin home-manager zellij;
        };
      };

      # Home Manager modules shared by every host
      sharedHomeModules = [
        ./modules/common
        ./modules/shell
        ./modules/agents
      ];

      mkDarwin =
        {
          hostName,
          hostPath,
          system ? "aarch64-darwin",
          user ? "legolas",
        }:
        nix-darwin.lib.darwinSystem {
          inherit system;
          specialArgs = mkSpecialArgs system // {
            inherit hostName user;
          };
          modules = [
            ./modules/darwin
            hostPath
            home-manager.darwinModules.home-manager
            {
              nixpkgs.hostPlatform = system;
              nixpkgs.overlays = overlays;
              networking.hostName = hostName;

              users.users.${user} = {
                name = user;
                home = "/Users/${user}";
              };

              home-manager = {
                useGlobalPkgs = true;
                useUserPackages = true;
                # Backup colliding regular files (e.g. manually staged ~/.pi/*) instead of failing apply
                backupFileExtension = "hm-bak";
                extraSpecialArgs = mkSpecialArgs system // {
                  inherit hostName user;
                };
                users.${user} = {
                  imports = sharedHomeModules ++ [
                    ./modules/darwin/home.nix
                  ];
                  home.username = user;
                  home.homeDirectory = "/Users/${user}";
                  home.stateVersion = "25.05";
                };
              };
            }
          ];
        };

      mkLinuxHome =
        {
          hostName,
          hostPath,
          user ? "legolas",
          system ? "x86_64-linux",
        }:
        home-manager.lib.homeManagerConfiguration {
          pkgs = import nixpkgs {
            inherit system overlays;
            config.allowUnfree = true;
          };
          extraSpecialArgs = mkSpecialArgs system // {
            inherit hostName user;
          };
          modules = sharedHomeModules ++ [
            ./modules/linux
            hostPath
            {
              home.username = user;
              home.homeDirectory = "/home/${user}";
              home.stateVersion = "25.05";
            }
          ];
        };

      darwinConfigurations = lib.mapAttrs (_name: host: mkDarwin host) inventory.darwin;
      homeConfigurations = lib.mapAttrs (_name: host: mkLinuxHome host) inventory.linux;
    in
    {
      inherit darwinConfigurations homeConfigurations;

      # Convenience: format checker when nix is available
      formatter = lib.genAttrs [ "aarch64-darwin" "x86_64-linux" "aarch64-linux" ] (
        system: nixpkgs.legacyPackages.${system}.nixfmt-rfc-style
      );
    };
}
