//! Create host modules and flake inventory from `nixup.toml` host entries.

use std::{
    fs,
    path::{
        Path,
        PathBuf,
    },
};

use crate::{
    config::{
        ApplyKind,
        HostEntry,
        HostOs,
        NixupConfig,
    },
    error::{
        CoreError,
        CoreResult,
    },
};

/// Result of syncing one host directory.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct HostSyncItem {
    /// Host id from config.
    pub id: String,
    /// Directory under `hosts/`.
    pub path: PathBuf,
    /// Whether `default.nix` was newly written.
    pub created: bool,
    /// Whether an existing file was left unchanged.
    pub skipped_existing: bool,
}

/// Full sync report.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct HostsSyncReport {
    /// Per-host outcomes.
    pub hosts: Vec<HostSyncItem>,
    /// Path written for inventory (if any).
    pub inventory_path: PathBuf,
    /// Whether inventory was written.
    pub inventory_written: bool,
}

/// Directory name under `hosts/` for a config entry (defaults to `id`).
#[must_use]
pub fn host_dir_name(host: &HostEntry) -> &str {
    host.id.as_str()
}

/// Default Nix system string when config omits `system`.
#[must_use]
pub fn default_system(host: &HostEntry) -> &'static str {
    match host.os {
        HostOs::Darwin => "aarch64-darwin",
        HostOs::Linux => "x86_64-linux",
    }
}

/// Nix username when config omits `user`.
#[must_use]
pub fn default_user(host: &HostEntry) -> &str {
    host.user.as_deref().unwrap_or("legolas")
}

/// Render `hosts/<id>/default.nix` body for a host entry.
#[must_use]
pub fn render_host_default_nix(host: &HostEntry) -> String {
    let hostname = host
        .match_hostnames
        .first()
        .map_or(host.id.as_str(), String::as_str);

    match host.apply_kind() {
        ApplyKind::Darwin => format!(
            r#"{{ lib, ... }}:
{{
  # Generated by `nixup hosts sync` from nixup.toml (host id: {id}).
  # Hostname should match: scutil --get LocalHostName
  networking.hostName = lib.mkDefault "{hostname}";
  networking.localHostName = lib.mkDefault "{hostname}";
  networking.computerName = lib.mkDefault "{hostname}";
}}
"#,
            id = host.id,
            hostname = escape_nix_string(hostname),
        ),
        ApplyKind::HomeManager => format!(
            r#"{{ ... }}:
{{
  # Generated by `nixup hosts sync` from nixup.toml (host id: {id}).
  home.sessionVariables.NIX_HOST = "{hostname}";
}}
"#,
            id = host.id,
            hostname = escape_nix_string(hostname),
        ),
    }
}

/// Render `hosts/inventory.nix` consumed by `flake.nix`.
#[must_use]
pub fn render_inventory_nix(config: &NixupConfig) -> String {
    let mut out = String::from(
        "# Generated by `nixup hosts sync` from nixup.toml — do not edit by hand.\n\
         # Re-run: nixup hosts sync\n\
         {\n  darwin = {\n",
    );

    for host in config
        .hosts
        .iter()
        .filter(|h| h.apply_kind() == ApplyKind::Darwin)
    {
        let dir = host_dir_name(host);
        let system = host
            .system
            .as_deref()
            .unwrap_or_else(|| default_system(host));
        let user = default_user(host);
        let host_name = host
            .match_hostnames
            .first()
            .map_or(host.id.as_str(), String::as_str);
        out.push_str(&format_inventory_entry(
            &host.flake_attr,
            host_name,
            dir,
            system,
            user,
        ));
    }

    out.push_str("  };\n  linux = {\n");

    for host in config
        .hosts
        .iter()
        .filter(|h| h.apply_kind() == ApplyKind::HomeManager)
    {
        let dir = host_dir_name(host);
        let system = host
            .system
            .as_deref()
            .unwrap_or_else(|| default_system(host));
        let user = default_user(host);
        let host_name = host
            .match_hostnames
            .first()
            .map_or(host.id.as_str(), String::as_str);
        out.push_str(&format_inventory_entry(
            &host.flake_attr,
            host_name,
            dir,
            system,
            user,
        ));
    }

    out.push_str("  };\n}\n");
    out
}

fn escape_nix_string(value: &str) -> String {
    value.replace('\\', "\\\\").replace('"', "\\\"")
}

fn format_inventory_entry(
    attr: &str,
    host_name: &str,
    dir: &str,
    system: &str,
    user: &str,
) -> String {
    format!(
        "    \"{attr}\" = {{\n      hostName = \"{host_name}\";\n      hostPath = ./{dir};\n      system = \"{system}\";\n      user = \"{user}\";\n    }};\n",
        attr = escape_nix_string(attr),
        host_name = escape_nix_string(host_name),
        dir = escape_nix_string(dir),
        system = escape_nix_string(system),
        user = escape_nix_string(user),
    )
}

/// Create missing host modules and write inventory under `flake_root/hosts/`.
///
/// When `force` is true, rewrite existing `default.nix` files.
pub fn sync_hosts(
    flake_root: &Path,
    config: &NixupConfig,
    force: bool,
) -> CoreResult<HostsSyncReport> {
    if config.hosts.is_empty() {
        return Err(CoreError::NoHosts);
    }

    let hosts_root = flake_root.join("hosts");
    fs::create_dir_all(&hosts_root).map_err(|source| CoreError::ConfigRead {
        path: hosts_root.clone(),
        source,
    })?;

    let mut items = Vec::new();

    for host in &config.hosts {
        let dir = hosts_root.join(host_dir_name(host));
        fs::create_dir_all(&dir).map_err(|source| CoreError::ConfigRead {
            path: dir.clone(),
            source,
        })?;

        let default_nix = dir.join("default.nix");
        let exists = default_nix.is_file();
        let created;
        let skipped_existing;

        if exists && !force {
            created = false;
            skipped_existing = true;
        } else {
            let body = render_host_default_nix(host);
            fs::write(&default_nix, body).map_err(|source| CoreError::ConfigRead {
                path: default_nix.clone(),
                source,
            })?;
            created = !exists;
            skipped_existing = false;
        }

        items.push(HostSyncItem {
            id: host.id.clone(),
            path: dir,
            created,
            skipped_existing,
        });
    }

    let inventory_path = hosts_root.join("inventory.nix");
    let inventory_body = render_inventory_nix(config);
    fs::write(&inventory_path, inventory_body).map_err(|source| CoreError::ConfigRead {
        path: inventory_path.clone(),
        source,
    })?;

    Ok(HostsSyncReport {
        hosts: items,
        inventory_path,
        inventory_written: true,
    })
}

#[cfg(test)]
mod tests {
    use tempfile::tempdir;

    use super::*;
    use crate::config::NixupConfig;

    fn sample_config() -> NixupConfig {
        let toml = r#"
schema_version = 1
[[hosts]]
id = "my-mac"
match_hostnames = ["my-mac"]
os = "darwin"
flake_attr = "my-mac"
[[hosts]]
id = "my-linux"
match_hostnames = []
os = "linux"
flake_attr = "me@linux"
apply = "home-manager"
user = "me"
system = "x86_64-linux"
"#;
        NixupConfig::parse_str(Path::new("t.toml"), toml).expect("parse")
    }

    #[test]
    fn render_inventory_contains_both_kinds() {
        let body = render_inventory_nix(&sample_config());
        assert!(body.contains("darwin = {"));
        assert!(body.contains("\"my-mac\""));
        assert!(body.contains("linux = {"));
        assert!(body.contains("\"me@linux\""));
        assert!(body.contains("user = \"me\""));
    }

    #[test]
    fn sync_creates_host_dirs_and_inventory() {
        let dir = tempdir().expect("temp");
        let report = sync_hosts(dir.path(), &sample_config(), false).expect("sync");
        assert_eq!(report.hosts.len(), 2);
        assert!(report.hosts.iter().all(|h| h.created));
        assert!(dir.path().join("hosts/my-mac/default.nix").is_file());
        assert!(dir.path().join("hosts/my-linux/default.nix").is_file());
        assert!(report.inventory_path.is_file());
        let inv = fs::read_to_string(&report.inventory_path).expect("read");
        assert!(inv.contains("my-mac"));
    }

    #[test]
    fn sync_skips_existing_without_force() {
        let dir = tempdir().expect("temp");
        let config = sample_config();
        sync_hosts(dir.path(), &config, false).expect("first");
        let path = dir.path().join("hosts/my-mac/default.nix");
        fs::write(&path, "# custom\n").expect("overwrite marker");
        let report = sync_hosts(dir.path(), &config, false).expect("second");
        let mac = report.hosts.iter().find(|h| h.id == "my-mac").expect("mac");
        assert!(mac.skipped_existing);
        assert_eq!(fs::read_to_string(&path).expect("read"), "# custom\n");
    }
}
